// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hihkxalmvlspowbshyxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpaGt4YWxtdmxzcG93YnNoeXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODg3OTUsImV4cCI6MjA2ODg2NDc5NX0.hkl5uJL5BKINIgRq9NbWQLoFiqTRlxU2OVMuAmORVmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});